typedef AsyncTask<T> = Future<T> Function();

class GlobalExceptionHandler {
  static Future<T> run<T>(AsyncTask<T> task) async {
    try {
      return await task();
    } catch (e, stack) {
      print('ðŸ›‘ Error global: $e');
      throw Exception('OcurriÃ³ un error inesperado. Intenta de nuevo.');
    }
  }
}
